name: demo.carchecp.in CI/CD

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  deploy:
    name: SCP deploy to VPS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload files to VPS using SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT || '22' }}
        source: "./"
        target: "/var/www/demo.carcheap.in"
        strip_components: 0
        overwrite: true
        rm: true
    
    - name: Change upload folder permission to 777 on VPS
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT || '22' }}
        script: |
          chmod -R 777 /var/www/demo.carcheap.in/uploaded-images/